version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "UserDataSwap"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17m51q7lf9ngj"
s3_prefix = "UserDataSwap"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
